### ISSUE TITLE
class inheritance highlighter gets confused by macros and comments

### ISSUE THREAD

**Issue by zrax** [jeff-hykin/cpp-textmate-grammar#121]
If a comment or macro exists anywhere after the `class` keyword and before the last parent class, the highlighting of parent classes and access specifiers is lost.

Examples:
![image](https://user-images.githubusercontent.com/714191/56622236-1ae9f580-65e4-11e9-94f1-7c0e12fce9b5.png)

**Comment by matter123** [comment]
With the first pattern, the grammar has no way of knowing that `DLLEXPORT` is actually __declspec(dllexport). `class __declspec(dllexport) ChildClass` should be highlighted correctly, however.

**Comment by MonaTheMonad** [comment]
The `alignas` specifier also seems to break highlighting in a similar manner.

**Comment by matter123** [comment]
The comment is fixed in 1.8.9.

**Comment by jeff-hykin** [comment]
<img width="779" alt="Screen Shot 2019-06-24 at 6 40 24 PM" src="https://user-images.githubusercontent.com/17692058/60058841-941ecb00-96af-11e9-95bd-aac99fd7f0a6.png">
Alignas is fixed. `DLLEXPORT` isn't fixed, but it doesn't cause a cascading break anymore. Since DLLEXPORT isn't a built in I don't plan to support it directly. OS/Library specific things (within textmate) would be a best fixed by a grammar injection extension so that people can toggle it on and off.
